### ISSUE TITLE
404 on http://www.irchelp.org/irchelp/ircii/

### ISSUE THREAD

**Issue by dequis** [irchelp/wio#38]
Found link in the reference section of https://en.wikipedia.org/wiki/IrcII (I know wikipedia could be fixed, but it's better to not have to)

http://www.irchelp.org/irchelp/ircii/ 404

http://www.irchelp.org/irchelp/clients/unix/ircii/ works

http://www.irchelp.org/irchelp/ircii/ircii.gif also 404, not sure what's the right one

Also, the ircii page here links to http://www.irchelp.org/irchelp/clients/unix/misc/telnet.html which is 404 too

**Comment by sdaugherty** [comment]
Thanks for reporting, Changed both hosting and underlying technologies, and some redirects have gotten lost in the shuffle.  I'll get them fixed shortly.

**Comment by sdaugherty** [comment]
The first 404 is fixed. The 2nd was a bad relative link, the link goes to the right place now.

**Comment by dequis** [comment]
Thanks! What about http://www.irchelp.org/irchelp/ircii/ircii.gif ? (also mentioned in the references of that wiki article)

**Comment by sdaugherty** [comment]
I'll get it tracked down and restored later this evening
