### ISSUE TITLE
Get started button not working

### ISSUE THREAD

**Issue by Warewolf96** [irchelp/wio#55]
http://www.irchelp.org/ "Get started" button on this website is redirecting to a File not found page(http://www.irchelp.org/irchelp/new2irc.html). Please get it fixed..

**Comment by bwiggs** [comment]
Seems like maybe low hanging fruit for some new contributor to take on? @sdaugherty any more info you could provide? Would this be new content to write or existing content to map and handle redirects?

**Comment by doctorBeast** [comment]
how should I fix this issue @bwiggs . If you have any clue please help

**Comment by wilhelmy** [comment]
Fixed
