### ISSUE TITLE
IRCHelp.org -- File not found.

### ISSUE THREAD

**Issue by Castir** [irchelp/wio#57]
I clicked on the IRCD link for information on the daemon, but this was the result.  This note was prompted by your request.

**Comment by BigBlueHat** [comment]
It mostly looks like several of the home page URLs are using `/irchelp/` prefixed URLs (ex: `/irchelp/ircd/`) but live at their own top-level folder such as `/ircd/`.

Consequently, adding `redirect_from:` statements to those indexes could fix the problem, but it'd be up to the admins/owners here what page structure they meant to have. It may be that it should go the other way: move `/ircd/` under `/irchelp/` and then add redirects for the top-level folder URLs.

Relatively simple change, though, once that's decided. 😄

**Comment by wilhelmy** [comment]
Should be fixed.
