### ISSUE TITLE
Error 404 in "Get started" link

### ISSUE THREAD

**Issue by 2H4D4M4NTHUS** [irchelp/wio#61]
There is a 404 redirect under the "Get started" button inside the homepage.

http://www.irchelp.org/irchelp/new2irc.html

**Comment by eragon512** [comment]
I'm facing the same error, as well

**Comment by MuhammadOmar125** [comment]
Me too

**Comment by bonnedav** [comment]
Me as well.

**Comment by xshotD** [comment]
Confirmed

**Comment by RalphCorderoy** [comment]
Found it when following the "Help for IRC newbies - General IRC help" link from http://lug.org.uk/IRC

**Comment by wilhelmy** [comment]
Fixed
