### ISSUE TITLE
The FAQs/new2irc link is not working ;-;

### ISSUE THREAD

**Issue by ghost** [irchelp/wio#70]
http://www.irchelp.org/irchelp/new2irc.html

**Comment by wilhelmy** [comment]
Please fix it and submit a pull request, if you can. Thanks!

**Comment by wilhelmy** [comment]
The file is right here, I don't understand why it does not end up being served: https://github.com/irchelp/irchelp.github.io/blob/gh-pages/irchelp/new2irc.html

**Comment by wilhelmy** [comment]
Moreover, neither http://www.irchelp.org/new2irc.html nor http://www.irchelp.org/irchelp/new2irc.html works. Is anyone here experienced with jekyll? I'd like to get at least the very basic documentation back on track. I don't think the finer details of distinguishing old ircd software are irchelp's job these days - that stuff can be found in the internet archive.

**Comment by wilhelmy** [comment]
I guess the answer is hidden somewhere in the output of https://travis-ci.org/irchelp/wio — see also #76

**Comment by DanielOaks** [comment]
Hmm, I'll take a look at this and see what I can do, throw in a few PRs 'n' all

**Comment by wilhelmy** [comment]
Fixed
