### ISSUE TITLE
Wrong element hilighted inside navigation

### ISSUE THREAD

**Issue by wilhelmy** [irchelp/wio#72]
If you click on an element inside the navbar, the new page will load but the "Home" element will always be hilighted/active.

**Comment by nih16agr** [comment]
Hi! May I look into this issue @wilhelmy  ??

**Comment by wilhelmy** [comment]
Of course. I'm bad at frontend web stuff, which is why it isn't done ;)

**Comment by nih16agr** [comment]
Thank you @wilhelmy ! I'll give an update in next 4 days positively. :)

**Comment by wilhelmy** [comment]
Thanks, guess I missed the notification on this ticket due to work issues flooding my github inbox
