### ISSUE TITLE
http://www.irchelp.org/irchelp/ircd/- File not found

### ISSUE THREAD

**Issue by dmklementiev** [irchelp/wio#81]
Navigating to http://www.irchelp.org/irchelp/ircd/ results in the following error:

File not found
The page you are trying to reach was not found on our server.

We redesigned our site recently, so this is probably our fault - submit an issue at https://github.com/irchelp/wio/issues and let us know where you found the link, and we’ll try to get it fixed as soon as possible

**Comment by toxicmender** [comment]
## Duplicates
#84 #82 
## Related
#75 #70 #69 #66 #76 

There seem to be too many of these, they seem to be having some problems with automatic static site generator (Jekyll)

**Comment by wilhelmy** [comment]
The new URL for /irchelp/ircd/* is /ircd/*, apparently. There is no redirect yet, but I've replaced the respective URLs in the entire repository with sed.

**Comment by wilhelmy** [comment]
At least the internal links work, but the redirect for any external links which still go to /irchelp/ircd instead of /ircd is still broken. Leaving this open until that's resolved.

**Comment by wilhelmy** [comment]
I guess I fixed these.
