### ISSUE TITLE
ircii basic command

### ISSUE THREAD

**Issue by MartinDelille** [irchelp/wio#86]
I just installed `ircii` but I can't find any information about the basic command (connect, join, send).

I can't even see the message in the channel I want to join (irc.freenode.org#ffmpeg).

Your website would be a good place to document this.

**Comment by wilhelmy** [comment]
There's definitely documentation for ircii here: http://www.irc.org/ftp/irc/clients/unix/ircII/ircii-current/ircii/help/

Have you tried /help?

I thought ircii fell out of fashion and it's definitely not the client I'd recommend to new users (even on the commandline, irssi and weechat seem easier to get into and more flexible).

However I'm definitely not opposed to merge ircii documentation if you or someone else submits a pull request :)

**Comment by MartinDelille** [comment]
Ok I was just looking for a terminal irc client! I'll go with weechat that look the most modern solution :-)

**Comment by MartinDelille** [comment]
PR on its way for weechat! https://github.com/irchelp/wio/pull/87
