### ISSUE TITLE
Links not opening in background. 

### ISSUE THREAD

**Issue by gattarman** [irchelp/wio#94]
I use Lime Chat 2.42 on my Macbook Air High Sierra 10.13.6. I use Google Chrome as my browser. The issue I am having is that when I click links on LimecChat, they open as the primary action. The link opens and LimeChat hides in the background. I would like to be able to open a number of links while on LImeChat without having the LimeChat box hide behind the browser. 

I checked under the LimeChat -> "Preferences" tab -> "Interface" -> "Open browser links in the background". I have the box checked mark for this option, but the links still become the primary response. I tried unchecking the box and testing the feature and the links still opened as the primary action. I tried "common + "click"" and the link still opens as a primary feature. In the past, I did not have this issue, but I am not sure why. if I could have help with this, instead of having to continuously access LimeChat when I click a link, that would be great.  Thank You

**Comment by wilhelmy** [comment]
I'm not sure anyone here uses limechat and this issue tracker isn't meant for actual support requests but issues with the website and not a lot of people read it so I guess your best bet would be contacting the limechat developers directly, especially if the checkbox doesn't do what it's supposed to do.
